# Generated by Django 3.2.9 on 2022-06-11 15:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=datetime.date(2022, 6, 12), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=datetime.date(2022, 6, 12), max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Not a valid phone number', regex='^01([0|1|6|7|8|9])([0-9]{4})([0-9]{4})')]),
            preserve_default=False,
        ),
    ]
